### ISSUE TITLE
Error while creating product 

### ISSUE THREAD

**Issue by shivani1111** [maximevaillancourt/trace#6] opened 2019-04-09 01:49 UTC
we have done these project on ubuntu system.so all is cleared upto running the program and getting the window of web3. we add details about product which we want to create but when we click on the  "create product" nothing is happening. so can you please tell us what is the problem and what is the solution for this bug??

**Comment by ghost** [comment] 2019-04-14 13:26
When I try to change something in react app, the page becomes blank.

**Comment by maximevaillancourt** [comment] 2019-04-14 21:51
Issue should be fixed with https://github.com/maximevaillancourt/trace/commit/8f830e5fc91f2c76b813c5ff116c1d6a29c09998.

MetaMask is now required as web3 is no longer injected automatically. The issue was caused by a [breaking change in web3's privacy model](https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8).

**Closed as completed by maximevaillancourt** 2019-04-14 21:51 UTC
